name: secret-scan
on:
  pull_request:
  push:
    branches: ["feature/lab3", "main"]
jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install gitleaks
        run: |
          curl -sSL https://raw.githubusercontent.com/gitleaks/gitleaks/main/install.sh | bash
          sudo mv gitleaks /usr/local/bin/
      - name: Run gitleaks
        run: gitleaks detect --source . --no-git --verbose --redact
